### ISSUE TITLE
Use GitHub actions to build and create installers

### ISSUE THREAD

**Issue by jackjansen** [jvdrhoof/WebRTCSFU#2]
Maybe also check whether it's worthwhile to use cmake to build things

**Comment by jackjansen** [comment]
Progress report: building with cmake works on all of win, Mac, linux. Building with GitHub Actions is also working. Creating a release with zip files for each target platform is ongoing.

**Comment by jackjansen** [comment]
The GitHub action doesn't have permission to create a release. @jvdrhoof this is something you have to fix, as the repo owner.

Here are instructions: https://forum.obsidian.md/t/create-release-error-in-github-actions/61310

Assign back to me afterwards, please.

**Comment by jvdrhoof** [comment]
Done. Can you check, @jackjansen?

**Comment by jackjansen** [comment]
Various issues found with v0.9:

- [ ] Mac executables are built for arm64, it seems runners `macos-latest` have switched to arm.
- [ ] Even on an M1 Mac trying to run `peer` will get a Killed signal straight away (if built with the ci/cd). Maybe quarantine?
- [ ] Windows executables have no `.exe` extension

**Comment by jackjansen** [comment]
The second bullet, the "Killed" one, turns out to be the quarantine bit again. Fix by running `xattr -d com.apple.quarantine` on the binaries. Probably also needed on the `.dylib`, unsure why I wasn't hit by this.

Note the self: we're going to need some sort of an install script that does this.
